name: dogma_rest_client
version: 0.0.2
description: RESTful HTTP client for Dart.
environment:
  sdk: '>=1.12.0 <2.0.0'
dev_dependencies:
  coverage: '>=0.7.2 <0.8.0'
  test: '>=0.12.5+1 <0.13.0'
author: Don Olmstead <don.j.olmstead@gmail.com>
homepage: http://dogma-dart.github.io/
